version: '1'

services:
  app:
    image: zahiriandii/devops-project:v2
    build:
      context: ..
    container_name: webapp-ctr
    depends_on:
      - postgresDB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresDB:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8081:8081

  postgresDB:
    image: postgres
    container_name: postgres-ctr
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - 5434:5434