
apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: prod
data:
  SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres-svc:5432/postgres' # //the-database-service-name:5432/postgres
---
apiVersion: v1
kind: Secret
metadata:
  namespace: prod
  name: database-secret
type: kubernetes.io/basic-auth
stringData:
  username: 'postgres'
  password: '12345678'
