name: Java CI with Maven and PostgreSQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Wait for PostgreSQL to start
      run: |
        timeout=60
        until nc -z localhost 5432 || [ $timeout -eq 0 ]; do
          echo "Waiting for PostgreSQL to start..."
          sleep 5
          timeout=$(($timeout - 5))
        done
    - name: Build with Maven
      run: mvn clean install
      env:
        DATABASE_URL: jdbc:postgresql://localhost:5432/postgres
        DATABASE_USERNAME: ${{ secrets.DB_USER }}
        DATABASE_PASSWORD: ${{ secrets.DB_PASSWORD }}

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: zahiriandii/devops-lab8:latest
