name: Docker Image CI for devops project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB-USERNAME }}
        password: ${{ secrets.DOCKERHUB-TOKEN }}
    - uses: actions/checkout@v4
    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: zahiriandii/devops-project:latest 
